version: 2
updates:
  - package-ecosystem: "github-actions"
    target-branch: "master"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 100
    labels:
      - "dependencies"
      - "github-actions"
      - "ci"
  # Dependabot doesn't yet support wildcards in `target-branch`, so we have to list each release branch manually.
  # https://github.com/dependabot/dependabot-core/issues/6890
  # https://github.com/dependabot/dependabot-core/issues/2511
  - package-ecosystem: "github-actions"
    target-branch: "release-1.10"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 100
    labels:
      - "dependencies"
      - "github-actions"
      - "ci"
  - package-ecosystem: "github-actions"
    target-branch: "release-1.11"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 100
    labels:
      - "dependencies"
      - "github-actions"
      - "ci"
  - package-ecosystem: "github-actions"
    target-branch: "release-1.12"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 100
    labels:
      - "dependencies"
      - "github-actions"
      - "ci"
  - package-ecosystem: "github-actions"
    target-branch: "release-1.13"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 100
    labels:
      - "dependencies"
      - "github-actions"
      - "ci"
