environment:
#  USEMSVC: "1"
  matrix:
  - ARCH: "i686"
  - ARCH: "x86_64"
    JULIA_CPU_CORES: 1
# Run win64 tests in serial for now to avoid #7942 causing timeouts

# Only build on master and PR's for now, not personal branches
# Whether or not PR's get built is determined in the webhook settings
branches:
  only:
    - master
    - release-0.3

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

clone_depth: 50

init:
# Carriage returns are bad
  - git config --global core.autocrlf input

cache:
# Cache any downloads from sourceforge because it's really unreliable
  - mingw-w32-bin-i686-20140102.7z
  - mingw-w64-bin-x86_64-20140102.7z
  - llvm-3.3-i686-w64-mingw32-juliadeps.7z
  - llvm-3.3-x86_64-w64-mingw32-juliadeps.7z
  - make-3.81-2-msys-1.0.11-bin.tar.lzma
  - jq.exe

build_script:
# Remove C:\MinGW\bin from the path, the version of MinGW installed on
# AppVeyor is not compatible with the cross-compiled Julia Windows binaries
  - set PATH=%PATH:C:\MinGW\bin;=%
#  - '"%VS120COMNTOOLS%\..\..\VC\vcvarsall.bat" x86_amd64'
# Since the AppVeyor VMs have Git installed, they have MSYS1
  - sh --login /c/projects/julia/contrib/windows/msys_build.sh

test_script:
  - usr\bin\julia -e "versioninfo()"
  - cd test && ..\usr\bin\julia runtests.jl all
