environment:
#  USEMSVC: "1"
  matrix:
  - ARCH: "i686"
  - ARCH: "x86_64"

# Only build on master and PR's for now, not personal branches
# Whether or not PR's get built is determined in the webhook settings
branches:
  only:
    - master
    - /release-.*/

skip_commits:
# Add [av skip] to commit messages for docfixes, etc to reduce load on queue
  message: /\[av skip\]/

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

clone_depth: 50

init:
# Carriage returns are bad
  - git config --global core.autocrlf input

cache:
# Cache any downloads from sourceforge because it's really unreliable
  - i686-4.9.2-release-win32-sjlj-rt_v4-rev3.7z
  - x86_64-4.9.2-release-win32-seh-rt_v4-rev3.7z
  - llvm-3.3-i686-w64-mingw32-juliadeps.7z
  - llvm-3.3-x86_64-w64-mingw32-juliadeps.7z
  - jq.exe

build_script:
# Remove C:\MinGW\bin from the path, the version of MinGW installed on
# AppVeyor is not compatible with the cross-compiled Julia Windows binaries
  - set PATH=%PATH:C:\MinGW\bin;=%
# Remove C:\Perl\bin from the path, otherwise it breaks shasum with an error
# Unable to find Digest::SHA or Digest::SHA::PurePerl
  - set PATH=%PATH:C:\Perl\bin;=%
#  - '"%VS120COMNTOOLS%\..\..\VC\vcvarsall.bat" x86_amd64'
# Since the AppVeyor VMs have Git installed, they have MSYS1
  - sh --login /c/projects/julia/contrib/windows/msys_build.sh

test_script:
  - usr\bin\julia -e "versioninfo()"
  - copy usr\lib\julia\sys.ji local.ji && usr\bin\julia -J local.ji -e "true" && del local.ji
  - cd test && ..\usr\bin\julia runtests.jl all && ..\usr\bin\julia runtests.jl pkg
