authors = "Stefan Karpinski <stefan@karpinski.org>"
desc = "The next-generation Julia package manager."
keywords = ["package", "management"]
license = "MIT"
name = "Pkg3"
repo = "https://github.com/StefanKarpinski/Pkg3.jl.git"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
