# This file is machine-generated - editing it directly is not advised

julia_version = "1.14.0-DEV"
manifest_format = "2.1"
project_hash = "4bf1a2bcb400675fbcf6d4672a47b29ec4f6e32f"

[[deps.Base64]]
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
version = "1.11.0"

    [deps.Base64.syntax]
    julia_version = "1.14.0-DEV.1581"

[[deps.Compiler]]
path = "../.."
uuid = "807dbc54-b67e-4c79-8afb-eafe4df6f2e1"
version = "0.1.1"

    [deps.Compiler.syntax]
    julia_version = "1.10.0"

[[deps.CompilerDevTools]]
deps = ["Compiler"]
path = "."
uuid = "92b2d91f-d2bd-4c05-9214-4609ac33433f"
version = "0.0.0"

    [deps.CompilerDevTools.syntax]
    julia_version = "1.14.0-DEV.1581"

[[deps.InteractiveUtils]]
deps = ["Markdown"]
uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
version = "1.11.0"

    [deps.InteractiveUtils.syntax]
    julia_version = "1.14.0-DEV.1581"

[[deps.JuliaSyntaxHighlighting]]
deps = ["StyledStrings"]
uuid = "ac6e5ff7-fb65-4e79-a425-ec3bc9c03011"
version = "1.13.0"

    [deps.JuliaSyntaxHighlighting.syntax]
    julia_version = "1.12.0"

[[deps.Logging]]
uuid = "56ddb016-857b-54e1-b83d-db4d58db5568"
version = "1.11.0"

    [deps.Logging.syntax]
    julia_version = "1.14.0-DEV.1581"

[[deps.Markdown]]
deps = ["Base64", "JuliaSyntaxHighlighting", "StyledStrings"]
uuid = "d6f4376e-aef5-505a-96c1-9c027394607a"
version = "1.11.0"

    [deps.Markdown.syntax]
    julia_version = "1.14.0-DEV.1581"

[[deps.Random]]
deps = ["SHA"]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
version = "1.11.0"

    [deps.Random.syntax]
    julia_version = "1.14.0-DEV.1581"

[[deps.SHA]]
uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce"
version = "1.0.0"

    [deps.SHA.syntax]
    julia_version = "1.0.0"

[[deps.Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
version = "1.11.0"

    [deps.Serialization.syntax]
    julia_version = "1.14.0-DEV.1581"

[[deps.StyledStrings]]
uuid = "f489334b-da3d-4c2e-b8f0-e476e12c162b"
version = "1.13.0"

    [deps.StyledStrings.syntax]
    julia_version = "1.11.0"

[[deps.Test]]
deps = ["InteractiveUtils", "Logging", "Random", "Serialization"]
uuid = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
version = "1.11.0"

    [deps.Test.syntax]
    julia_version = "1.14.0-DEV.1581"
