name = "JuliaSyntax"
uuid = "70703baa-626e-46a2-a12c-08ffd08c73b4"
authors = ["Chris Foster <chris42f@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Tokenize = "0796e94c-ce3b-5d07-9a54-7f471281c624"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
