name = "JuliaSyntax"
uuid = "70703baa-626e-46a2-a12c-08ffd08c73b4"
authors = ["Claire Foster <aka.c42f@gmail.com> and contributors"]
version = "0.4.6"

[compat]
Serialization = "1.0"
julia = "1.0"

[deps]

[extras]
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Serialization", "Logging"]
