[[Base64]]
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"

[[Compat]]
git-tree-sha1 = "45abe32cc7bcf2632dda2fb2549c7060811ea0ec"
repo-rev = "kc/Compat_fix"
repo-url = "https://github.com/JuliaLang/Compat.jl.git"
uuid = "34da2185-b29b-5c13-b0c7-acf172513d20"
version = "0.65.0+"

    [Compat.deps]
    Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
    Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
    DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
    Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
    InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
    IterativeEigensolvers = "de555fa4-b82f-55e7-8b71-53f60bbc027d"
    LibGit2 = "76f85450-5226-5b5a-8eaa-529ad045b433"
    Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
    LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
    Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
    Mmap = "a63ad114-7e13-5084-954f-fe012c677804"
    OldPkg = "fe1c5a76-5840-53d2-82f9-288dd83ce2ce"
    Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
    Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
    REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
    Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
    Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
    SharedArrays = "1a1011a3-84de-559e-8e89-a11a2f7dc383"
    Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
    SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
    SuiteSparse = "4607b0f0-06f3-5cda-b6b1-a6196a1729e9"
    Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
    UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
    Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[[Dates]]
uuid = "ade2ca70-3891-5945-98fb-dc099432e06a"

[[DelimitedFiles]]
uuid = "8bb1440f-4735-579b-a4ab-409b98df4dab"

[[Distributed]]
uuid = "8ba89e20-285c-5b6f-9357-94700520ee1b"

[[DocStringExtensions]]
deps = ["Compat"]
git-tree-sha1 = "0e9a957a5c1cc5d06e54aab3b8b9c4c495253269"
uuid = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
version = "0.4.4"

[[Documenter]]
deps = ["Compat", "DocStringExtensions", "Logging", "REPL"]
git-tree-sha1 = "4fc4abdb5ac20ece943ff6e0a7e2a254d148f434"
uuid = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
version = "0.18.0"

[[InteractiveUtils]]
uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[[IterativeEigensolvers]]
uuid = "de555fa4-b82f-55e7-8b71-53f60bbc027d"

[[LibGit2]]
uuid = "76f85450-5226-5b5a-8eaa-529ad045b433"

[[Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[LinearAlgebra]]
uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[[Logging]]
uuid = "56ddb016-857b-54e1-b83d-db4d58db5568"

[[Markdown]]
uuid = "d6f4376e-aef5-505a-96c1-9c027394607a"

[[Mmap]]
uuid = "a63ad114-7e13-5084-954f-fe012c677804"

[[Printf]]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[[REPL]]
uuid = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[[Random]]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[[SharedArrays]]
uuid = "1a1011a3-84de-559e-8e89-a11a2f7dc383"

[[Sockets]]
uuid = "6462fe0b-24de-5631-8697-dd941f90decc"

[[SparseArrays]]
uuid = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[[SuiteSparse]]
uuid = "4607b0f0-06f3-5cda-b6b1-a6196a1729e9"

[[Test]]
uuid = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[[UUIDs]]
uuid = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[[Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"
