[deps]
JuliaInterpreter = "aa1ae85d-cabe-5617-a682-6adf51b2e16a"
LoweredCodeUtils = "6f1432cf-f94c-5a45-995e-cdbf5db27b0b"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[sources]
JuliaInterpreter = {rev = "master", url = "https://github.com/JuliaDebug/JuliaInterpreter.jl.git"}
LoweredCodeUtils = {rev = "master", url = "https://github.com/JuliaDebug/LoweredCodeUtils.jl.git"}
Revise = {rev = "master", url = "https://github.com/timholy/Revise.jl.git"}
