name = "InteractiveUtils"
uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[deps]
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random"]
