name = "LibUnwind_jll"
uuid = "745a5e78-f969-53e9-954f-d19f2f74f4e3"
version = "1.8.2+0"

[deps]
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
CompilerSupportLibraries_jll = "e66e0078-7015-5450-92f7-15fbd957f2ae"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Zlib_jll = "83775a58-1f1d-513f-b197-d71354ab007a"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
