name = "JuliaLowering"
uuid = "f3c80556-a63f-4383-b822-37d64f81a311"
authors = ["Claire Foster <aka.c42f@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
JuliaSyntax = "70703baa-626e-46a2-a12c-08ffd08c73b4"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
FileWatching = "7b1f6079-737a-58dc-b8bc-7a2ca5c1b5ee"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[targets]
test = ["Test", "FileWatching", "Markdown", "REPL"]
