name = "libLLVM_jll"
uuid = "8f36deef-c2a5-5394-99ed-8e07531fb29a"
version = "20.1.2+1"

[deps]
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
CompilerSupportLibraries_jll = "e66e0078-7015-5450-92f7-15fbd957f2ae"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Zlib_jll = "83775a58-1f1d-513f-b197-d71354ab007a"
Zstd_jll = "3161d3a3-bdf6-5164-811a-617609db77b4"

[compat]
CompilerSupportLibraries_jll = "1.3.0"
Zlib_jll = "1"
Zstd_jll = "1.5.7"
julia = "1.13"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
