name = "LibGit2"
uuid = "76f85450-5226-5b5a-8eaa-529ad045b433"

[deps]
LibGit2_jll = "e37daf67-58a4-590a-8e99-b0245dd2ffc5"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random", "Serialization", "Sockets"]
