name = "OpenLibm_jll"
uuid = "05823500-19ac-5b8b-9628-191a04bc5112"
version = "0.7.4+0"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"

[compat]
julia = "1.0"
